@startuml
actor User
boundary login_view
control LoginController
entity UserModel

User -> login_view : yêu cầu đăng nhập
activate User
activate login_view
login_view --> User :yêu cầu nhập email, password
deactivate login_view
User -> login_view : nhập email, pass, bấm nút đăng nhập
deactivate User
activate login_view
login_view -> LoginController: gửi thông tin người dùng nhập
deactivate login_view
activate LoginController
LoginController -> LoginController : validate
LoginController -> UserModel : lấy dữ liệu
activate UserModel
UserModel --> LoginController : trả dữ liệu
deactivate UserModel
LoginController --> login_view: trả kết qủa kiểm tra
deactivate LoginController
activate login_view
login_view --> User: Thông báo kết quả đăng nhập
deactivate login_view

@enduml