@startuml
actor Admin
boundary list_packs_view
boundary edit_premium_pack_view
control PremiumPackController
entity PremiumPackModel

activate Admin
Admin -> list_packs_view: yêu cầu xem danh sách pack
activate list_packs_view
list_packs_view --> Admin: Hiển thị danh sách pack
Admin -> list_packs_view: Bấm nút sửa trên pack
list_packs_view -> edit_premium_pack_view : chuyển hướng sang trang sửa pack
deactivate list_packs_view
activate edit_premium_pack_view
edit_premium_pack_view --> Admin : hiển thị nội dung pack
deactivate edit_premium_pack_view
Admin -> edit_premium_pack_view : sửa dữ liệu pack, bấm nút lưu
deactivate Admin
activate edit_premium_pack_view
edit_premium_pack_view -> PremiumPackController: gửi thông tin
deactivate edit_premium_pack_view
activate PremiumPackController
PremiumPackController -> PremiumPackController : validate
PremiumPackController -> PremiumPackModel : lưu dữ liệu
activate PremiumPackModel
PremiumPackModel --> PremiumPackController : trả dữ liệu đã lưu
deactivate PremiumPackModel
PremiumPackController --> edit_premium_pack_view: trả kết qủa lưu pack
deactivate PremiumPackController
activate edit_premium_pack_view

edit_premium_pack_view --> Admin: hiển thị pack đã sửa
activate Admin
deactivate edit_premium_pack_view
deactivate Admin

@enduml