@startuml
actor User
control LoginController
boundary auth.login
entity UserModel

User -> LoginController : go to login page
activate User
activate LoginController
LoginController -> auth.login:showLoginForm()
deactivate LoginController
activate auth.login
auth.login -> auth.login:render()
auth.login --> User
deactivate auth.login
User -> LoginController: email, password
activate LoginController
LoginController -> LoginController : login()
LoginController -> LoginController : validate()
LoginController -> UserModel : attemptLogin()
activate UserModel
UserModel --> LoginController : login ok
deactivate UserModel
LoginController --> User: return to home
deactivate LoginController

@enduml