@startuml
actor User
control RegisterController
boundary auth.register
entity UserModel

User -> RegisterController : go to login page
activate User
activate RegisterController
RegisterController -> auth.register:showRegistrationForm ()
deactivate RegisterController
activate auth.register
auth.register -> auth.register:render()
auth.register --> User
deactivate auth.register
User -> RegisterController: email, password, name...
activate RegisterController
RegisterController -> RegisterController : register()
RegisterController -> RegisterController : validate()
RegisterController -> UserModel
activate UserModel
UserModel->UserModel:create()
UserModel --> RegisterController : login ok
deactivate UserModel
RegisterController --> User: return to home
deactivate RegisterController

@enduml