@startuml
actor User
control ResetPasswordController
boundary auth.passwords.email
boundary auth.passwords.reset
entity UserModel

User -> ResetPasswordController : go to reset password page
activate User
activate ResetPasswordController
ResetPasswordController->auth.passwords.email: showLinkRequestForm()
deactivate ResetPasswordController
activate auth.passwords.email
auth.passwords.email -> auth.passwords.email:render()
auth.passwords.email -->User
deactivate auth.passwords.email
User -> ResetPasswordController : email
activate ResetPasswordController
ResetPasswordController ->ResetPasswordController:validate()
ResetPasswordController -> ResetPasswordController:sendResetLinkEmail()
ResetPasswordController -->User:
deactivate ResetPasswordController

User -> ResetPasswordController: go to reset password URL
activate ResetPasswordController
ResetPasswordController -> auth.passwords.reset:showResetForm()
deactivate ResetPasswordController
activate auth.passwords.reset
auth.passwords.reset -> auth.passwords.reset:render()
auth.passwords.reset --> User :
deactivate auth.passwords.reset
User -> ResetPasswordController: new password
activate ResetPasswordController
ResetPasswordController ->ResetPasswordController:validate()
ResetPasswordController ->UserModel:reset()
activate UserModel
UserModel -> UserModel: update_password()
UserModel --> ResetPasswordController :
deactivate UserModel
ResetPasswordController --> User: return to login page
deactivate ResetPasswordController

@enduml