@startuml
actor User
boundary edit_offer_view
control OfferController
entity OfferModel

User -> edit_offer_view : create new offer
activate User
activate edit_offer_view
edit_offer_view --> User : new offer form
deactivate edit_offer_view
User -> edit_offer_view : new offer's info
deactivate User
activate edit_offer_view
edit_offer_view -> OfferController: offer's info
deactivate edit_offer_view
activate OfferController
OfferController -> OfferController : validate data
OfferController -> OfferModel : save data
activate OfferModel
OfferModel -> OfferModel: save new offer
OfferModel --> OfferController : save ok
deactivate OfferModel
OfferController --> User: return home
deactivate OfferController

@enduml