@startuml
actor User
boundary list_offers_view
control OfferController
entity OfferModel

activate User
User -> list_offers_view: view offer list
activate list_offers_view
User <-- list_offers_view: offer list
User -> list_offers_view: click hide offer
User <-- list_offers_view: confirm box
User -> list_offers_view: click confirm
list_offers_view-> OfferController: request delete offer
deactivate list_offers_view
activate OfferController
OfferController -> OfferController : validate
OfferController -> OfferModel : hide offer
activate OfferModel
OfferModel ->OfferModel:soft delete offer
OfferModel --> OfferController : deleted
deactivate OfferModel
OfferController --> User: return to offer list
deactivate OfferController
deactivate User

@enduml