@startuml
actor User
control OfferController
boundary list_offers_view
entity OfferModel

activate User
User -> OfferController: view offer list
activate OfferController
OfferController -> list_offers_view:manage()
deactivate OfferController
activate list_offers_view
list_offers_view -> list_offers_view:render()
list_offers_view -->User
deactivate list_offers_view
User -> OfferController: click hide offer
activate OfferController
OfferController -> OfferModel : hide()
activate OfferModel
OfferModel ->OfferModel:soft_delete()
OfferModel --> OfferController
deactivate OfferModel
OfferController --> User: return to offer list
deactivate OfferController
deactivate User

@enduml