@startuml
actor User
boundary offer_detail_view
control OfferController
entity UserOfferLike

activate User
User -> offer_detail_view: go to offer detail page
activate offer_detail_view
User <-- offer_detail_view: offer detail
User -> offer_detail_view: click like
deactivate User
offer_detail_view ->OfferController:like offer
deactivate offer_detail_view
activate OfferController
OfferController -> OfferController : validate
OfferController -> UserOfferLike : save like
activate UserOfferLike
UserOfferLike -> UserOfferLike:save
UserOfferLike --> OfferController : save ok
deactivate UserOfferLike
activate offer_detail_view
offer_detail_view <-- OfferController : update like button
offer_detail_view -->User :update like button
deactivate offer_detail_view
@enduml