@startuml
actor User
boundary login_view
control LoginController
entity UserModel

User -> login_view : input email, password
deactivate User
activate login_view
login_view -> LoginController: email, password
deactivate login_view
activate LoginController
LoginController -> LoginController : validation
LoginController -> UserModel : get user's data
activate UserModel
UserModel --> LoginController : user's data
deactivate UserModel
LoginController --> login_view: successful login
deactivate LoginController
activate login_view
login_view --> User: Login success alert, redirect to home
deactivate login_view

@enduml