@startuml
actor Admin
boundary list_offer_view
control OfferController
entity OfferModel

Admin -> list_offer_view : view pending offers
activate Admin
activate list_offer_view
list_offer_view --> Admin : pending offers list
deactivate list_offer_view
Admin -> list_offer_view : click accept
deactivate Admin
activate list_offer_view
list_offer_view -> OfferController: accept
deactivate list_offer_view
activate OfferController
OfferController -> OfferController : validation
OfferController -> OfferModel : save accept
activate OfferModel
OfferModel --> OfferController : saved
deactivate OfferModel
OfferController --> list_offer_view: return ok
deactivate OfferController
activate list_offer_view
list_offer_view --> Admin: alert saved, return to list
deactivate list_offer_view

@enduml